### ISSUE TITLE
Broken pipe @ io_write - <STDOUT> (Errno::EPIPE)

### ISSUE THREAD

**Issue by rubyconvict** [huangw/mongoid-erd-gem#4]
```
(...)/vendor/bundle/ruby/2.2.0/gems/rviz-0.1.0/lib/rviz/graph.rb:93:in `write': Broken pipe @ io_write - <STDOUT> (Errno::EPIPE)
  from (...)/vendor/bundle/ruby/2.2.0/gems/rviz-0.1.0/lib/rviz/graph.rb:93:in `puts'
  from (...)/vendor/bundle/ruby/2.2.0/gems/rviz-0.1.0/lib/rviz/graph.rb:93:in `block in output'
  from (...)/vendor/bundle/ruby/2.2.0/gems/rviz-0.1.0/lib/rviz/graph.rb:93:in `each'
  from (...)/vendor/bundle/ruby/2.2.0/gems/rviz-0.1.0/lib/rviz/graph.rb:93:in `output'
  from (...)/vendor/bundle/ruby/2.2.0/gems/mongoid-erd-0.0.8/lib/mongoid_erd.rb:217:in `output'
  from (...)/vendor/bundle/ruby/2.2.0/gems/mongoid-erd-0.0.8/bin/merd:59:in `<top (required)>'
  from (...)/vendor/bundle/ruby/2.2.0/bin/merd:23:in `load'
  from (...)/vendor/bundle/ruby/2.2.0/bin/merd:23:in `<main>'
```

**Comment by nofxx** [comment]
You're piping to a nonexistent folder perhaps?
`> docs/foo.png` , "docs" should be created first.
